import { useMemo } from "react";
import { Equal, Expect } from "../helpers/type-utils";

// originally this was returning a function of string[]
// looking at the useMemo TS declaration we can see it is a generic that just returns a function and the return type T
// this means we can remove the type argument OR we can just pass string[] as the type argument
export const Component = () => {
  const autoGeneratedIds = useMemo(() => {
    // generate 100 random string uuid's
    return Array.from({ length: 100 }, () =>
      Math.random().toString(36).substr(2, 9)
    );
  }, []);

  type test = Expect<Equal<typeof autoGeneratedIds, string[]>>;
};
